name: Deploy Docs Site

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "pyproject.toml"
      - "mkdocs.yml"
      - "docs/**"
      - "**.md"

jobs:
  build-mkdocs:
    runs-on: ubuntu-latest
    if: ${{ github.event.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up workspace
        uses: ./.github/actions/setup-workspace

      - name: Build site pages
        run: |
          poetry run mkdocs --version
          poetry run mkdocs build --clean --strict

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy-pages:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs: build-mkdocs

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
