name: Pre-commit

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up workspace
        uses: ./.github/actions/setup-workspace

      - name: Run pre-commit
        run: |
          pip install pre-commit
          pre-commit run --all-files --verbose
